### PR TITLE
PRJ-523 License audit

### PR DESCRIPTION
**Pull request by Avvessalom**

### CODE REVIEW

**Review by SerVB — CHANGES_REQUESTED** [review]
Well, I've moved to the page and see something isn't right.

No dependencies found:

image

For licenses:
1. Finds GPLv2 only, but why? We have GPLv2+CPL.
2. Doesn't allow to see locations.

image

So the current state looks not working. Please try to resolve these problems. Maybe contacting Fossa team will help as they suggest

**Comment by Avvessalom** [comment]
Qodana team said they will add a license audit to their application

**Comment by SerVB** [comment]
Do we have their ticket to watch? Let's leave a link here

**Comment by Avvessalom** [comment]
> Do we have their ticket to watch? Let's leave a link here and in [JetBrains/projector-client#45](https://github.com/JetBrains/projector-client/pull/45)

I didn't find a similar ticket on youtrack, but in the dialogue in the slack they assured me that they would add a license audit to the app

**Comment by SerVB** [comment]
Please create that ticket then ¯\_(ツ)_/¯

Because no ticket = no task, and we don't want wait forever ;)

**Comment by Avvessalom** [comment]
[ticket](https://youtrack.jetbrains.com/issue/QD-1124)

**Pull request closed without merging**
